const ADD_MARKUP='ADD_MARKUP'
const EDIT_MARKUP='EDIT_MARKUP'
const DELETE_MARKUP='DELETE_MARKUP'
const UPDATE_VALUE='UPDATE_VALUE'
const PERFORM_SEARCH='PERFORM_SEARCH'
const EMPTY_SEARCH='EMPTY_SEARCH'
const OPEN_EDITOR='OPEN_EDITOR'
const CLOSE_EDITOR='CLOSE_EDITOR'
const UPDATE_MARKUP_FORM='UPDATE_MARKUP_FORM'
export {
    ADD_MARKUP,EDIT_MARKUP,DELETE_MARKUP,UPDATE_VALUE,PERFORM_SEARCH,EMPTY_SEARCH,OPEN_EDITOR,CLOSE_EDITOR,UPDATE_MARKUP_FORM
}