const ADD_EMAIL='ADD_EMAIL'
const EDIT_EMAIL='EDIT_EMAIL'
const DELETE_EMAIL='DELETE_EMAIL'
const OPEN_MODAL='OPEN_MODAL'
const CLOSE_MODAL='CLOSE_MODAL'
const OPEN_EDITOR='OPEN_EDITOR'
const CHANGE_TAB='CHANGE_TAB'
const PERFORM_SEARCH='PERFORM_SEARCH'
const UPDATE_VALUE='UPDATE_VALUE'
const EMPTY_SEARCH='EMPTY_SEARCH'
export {
    ADD_EMAIL,EDIT_EMAIL,DELETE_EMAIL,OPEN_MODAL,CLOSE_MODAL,OPEN_EDITOR,CHANGE_TAB,PERFORM_SEARCH,UPDATE_VALUE,EMPTY_SEARCH
}