const ADD_EMAIL='ADD_EMAIL'
const EDIT_EMAIL='EDIT_EMAIL'
const DELETE_EMAIL='DELETE_EMAIL'
const OPEN_MODAL='OPEN_MODAL'
const CLOSE_MODAL='CLOSE_MODAL'

export {
    ADD_EMAIL,EDIT_EMAIL,DELETE_EMAIL,OPEN_MODAL,CLOSE_MODAL
}